document.write( '                    <div class=\"sidebar_box\">\n' );
document.write( '\n' );
document.write( '                        <div class=\"sb_title\">Menu</div>\n' );
document.write( '                        <div class=\"sb_content\">\n' );
document.write( '                            <div id=\"main_menu\">\n' );
document.write( '                                <ul>\n' );
document.write( '                                    <li><a href=\"index.html\" target=\"_parent\" class=\"current\">Home</a></li>\n' );
document.write( '                                    <li class=\"isFolder\">\n' );
document.write( '                                        Locale\n' );
document.write( '                                        <ul>\n' );
document.write( '								 		    <li><a href=\"index-inner.html\">English</a></li>\n' );
document.write( '                                            <li><a href=\"index-inner_tw.html\">繁體中文</a></li>\n' );
document.write( '											<li><a href=\"index-inner_cn.html\">简体中文</a></li>\n' );
document.write( '                                        </ul>\n' );
document.write( '                                    </li>									\n' );
document.write( '                                    <li class=\"isFolder\">\n' );
document.write( '                                        About\n' );
document.write( '                                        <ul>\n' );
document.write( '                                            <li><a href=\"index-inner-features.html\"> Features of Game Mining、Dev. Roadmap</a></li>\n' );
document.write( '											<li><a href=\"video.html\" target=\"_blank\"> Demo Video of Desktop APP</a></li>\n' );
document.write( '                                        </ul>\n' );
document.write( '                                    </li>																		\n' );
document.write( '                                    <li class=\"isFolder\">\n' );
document.write( '                                        Games (No Battle-Free Try)\n' );
document.write( '                                        <ul>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Puzzle & Arcade \n' );
document.write( '                                                <ul>												\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/space_adventure_pinball/\" target=\"_blank\">Space Adventure Pinball</a></li>													\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/battleship_war/\" target=\"_blank\">Battleship War</a></li>	\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>										\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Sport \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/penalty_kicks/\" target=\"_blank\">Penalty Kicks </a></li>																									\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/baseball_pro/\" target=\"_blank\">Baseball Pro </a></li>	\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/downhill_ski/\" target=\"_blank\">Downhill_Ski </a></li>															\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>										\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Casino \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/horse_racing/\" target=\"_blank\">Horse Racing</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/greyhound_racing/\" target=\"_blank\">Greyhound Racing</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/blackjack/\" target=\"_blank\">Blackjack</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/baccarat/\" target=\"_blank\">Baccarat</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/pai_gow_poker/\" target=\"_blank\">Pai Gow Poker</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/craps/\" target=\"_blank\">Craps</a></li>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/slot_the_fruits/\" target=\"_blank\">Slot Machine-Fruits</a></li>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/roulette/\" target=\"_blank\">3D Roulette</a></li>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/jacks_or_better/\" target=\"_blank\">Jacks or Better</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>										\n' );
document.write( '                                        </ul>\n' );
document.write( '                                    </li>\n' );
document.write( '                                    <li class=\"isFolder\">\n' );
document.write( '									   APP (Welcome to join or recommend) \n' );
document.write( '                                         <ul>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Daily\n' );
document.write( '                                                <ul>\n' );
document.write( '												   <li><a href=\"https://matrix.org/\" target=\"_blank\">Open and Secure Decentralized Real-time Communication</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Exchange \n' );
document.write( '                                                <ul>\n' );
document.write( '												   <li><a href=\"https://usddex.github.io/exchange/\" target=\"_blank\">USDDex @ BSC Binance</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '										    </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                E-commerce\n' );
document.write( '                                                <ul>\n' );
document.write( '                                                   <li><a href=\"https://www.gatsbyjs.com/docs/\" target=\"_blank\">Gatsby</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Business Management\n' );
document.write( '                                                <ul>\n' );
document.write( '                                                   <li><a href=\"https://erpnext.com/\" target=\"_blank\">Most Agile ERP</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Education/Training   \n' );
document.write( '                                                <ul>\n' );
document.write( '												    <li><a href=\"https://www.adaptlearning.org/\" target=\"_blank\">Adapt Learning</a></li>\n' );
document.write( '													<li><a href=\"https://github.com/runbytech/ultron-ele\" target=\"_blank\">Fastest LMS Engine</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Computer Aided Design, CAD\n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Computer Aided Manufacturing, CAM\n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Computer Aided Engineering, CAE\n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Electronic Design Automation, EDA\n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                Robotics\n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                        </ul> 									   									   \n' );
document.write( '                                    </li>\n' );
document.write( '									<li class=\"isFolder\">\n' );
document.write( '                                        Download\n' );
document.write( '										<ul>\n' );
document.write( '										 <li><a href=\"https://github.com/USDDex/usddex.github.io/releases/tag/v2021.08-preview\" target=\"_blank\">v2021.08 Preview</a></li>	 \n' );
document.write( '										</ul> \n' );
document.write( '                                    </li>									\n' );
document.write( '									<li class=\"isFolder\">\n' );
document.write( '                                        Discussion\n' );
document.write( '										<ul>\n' );
document.write( '										 <li><a href=\"https://usdd.boards.net\" target=\"_blank\">USDD Forum</a></li>	 \n' );
document.write( '										</ul> \n' );
document.write( '                                    </li>\n' );
document.write( '                                </ul>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"sb_bottom\"></div>\n' );
document.write( '                    </div>' );
