document.write( '                    <div class=\"sidebar_box\">\n' );
document.write( '\n' );
document.write( '                        <div class=\"sb_title\">功能表</div>\n' );
document.write( '                        <div class=\"sb_content\">\n' );
document.write( '                            <div id=\"main_menu\">\n' );
document.write( '                                <ul>\n' );
document.write( '                                    <li><a href=\"index.html\" target=\"_parent\" class=\"current\">首頁</a></li>\n' );
document.write( '                                    <li class=\"isFolder\">\n' );
document.write( '                                        地區\n' );
document.write( '                                        <ul>\n' );
document.write( '								 		    <li><a href=\"index-inner.html\">English</a></li>\n' );
document.write( '                                            <li><a href=\"index-inner_tw.html\">繁體中文</a></li>\n' );
document.write( '											<li><a href=\"index-inner_cn.html\">简体中文</a></li>\n' );
document.write( '                                        </ul>\n' );
document.write( '                                    </li>									\n' );
document.write( '                                    <li class=\"isFolder\">\n' );
document.write( '                                        關於\n' );
document.write( '                                        <ul>\n' );
document.write( '                                            <li><a href=\"index-inner-features_tw.html\"> 遊戲挖礦特色、發展藍圖</a></li>\n' );
document.write( '											<li><a href=\"video.html\" target=\"_blank\"> 桌上版本運行影片</a></li>\n' );
document.write( '                                        </ul>\n' );
document.write( '                                    </li>																		\n' );
document.write( '                                    <li class=\"isFolder\">\n' );
document.write( '                                        遊戲 (無對戰-自由試玩)\n' );
document.write( '                                        <ul>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                益智\n' );
document.write( '                                                <ul> 												\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/space_adventure_pinball/\" target=\"_blank\">太空探險彈珠台</a></li>													\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/battleship_war/\" target=\"_blank\">導彈戰艦</a></li>	\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>										\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                運動 \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/penalty_kicks/\" target=\"_blank\">罰踢球</a></li>																									\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/baseball_pro/\" target=\"_blank\">打棒球</a></li>	\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/downhill_ski/\" target=\"_blank\">滑雪避障賽</a></li>															\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>										\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                娛樂場 \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/horse_racing/\" target=\"_blank\">賽馬</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/greyhound_racing/\" target=\"_blank\">賽狗</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/blackjack/\" target=\"_blank\">21點</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/baccarat/\" target=\"_blank\">百家樂</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/pai_gow_poker/\" target=\"_blank\">牌九撲克</a></li>\n' );
document.write( '													<li><a href=\"https://showcase.codethislab.com/games/craps/\" target=\"_blank\">雙骰子/花旗骰</a></li>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/slot_the_fruits/\" target=\"_blank\">水果拉霸</a></li>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/roulette/\" target=\"_blank\">3D 輪盤</a></li>\n' );
document.write( '                                                    <li><a href=\"https://showcase.codethislab.com/games/jacks_or_better/\" target=\"_blank\">傑克或更大</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>										\n' );
document.write( '                                        </ul>\n' );
document.write( '                                    </li>\n' );
document.write( '                                    <li class=\"isFolder\">\n' );
document.write( '									    APP (歡迎加入或推薦)\n' );
document.write( '                                        <ul>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                日常 \n' );
document.write( '                                                <ul>\n' );
document.write( '												   <li><a href=\"https://matrix.org/\" target=\"_blank\">開放安全的去中心化及時通訊</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                交易所 \n' );
document.write( '                                                <ul>\n' );
document.write( '												   <li><a href=\"https://uniswap.org/\" target=\"_blank\">Uniswap</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '										    </li>\n' );
document.write( '                                            </li>											\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                電子商務 \n' );
document.write( '                                                <ul>\n' );
document.write( '												    <li><a href=\"https://www.gatsbyjs.com/docs/\" target=\"_blank\">Gatsby</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                企業管理 \n' );
document.write( '                                                <ul>\n' );
document.write( '												    <li><a href=\"https://erpnext.com/\" target=\"_blank\">Most Agile ERP</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                教育/培訓 \n' );
document.write( '                                                <ul>\n' );
document.write( '												    <li><a href=\"https://www.adaptlearning.org/\" target=\"_blank\">Adapt Learning</a></li>\n' );
document.write( '													<li><a href=\"https://github.com/runbytech/ultron-ele\" target=\"_blank\">Fastest LMS Engine</a></li>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                電腦輔助設計 \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                電腦輔助製造 \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                電腦輔助工程 \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                電子設計自動化 \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                            <li class=\"isFolder\">\n' );
document.write( '                                                機器人 \n' );
document.write( '                                                <ul>\n' );
document.write( '                                                </ul>\n' );
document.write( '                                            </li>\n' );
document.write( '                                        </ul>																					\n' );
document.write( '                                    </li>									\n' );
document.write( '									<li class=\"isFolder\">\n' );
document.write( '                                        下載\n' );
document.write( '										<ul>\n' );
document.write( '										 <li><a href=\"https://github.com/USDDex/usddex.github.io/releases/tag/v2021.08-preview\" target=\"_blank\">v2021.08 預覽版</a></li>	 \n' );
document.write( '										</ul> \n' );
document.write( '                                    </li>\n' );
document.write( '									<li class=\"isFolder\">\n' );
document.write( '                                        討論\n' );
document.write( '										<ul>\n' );
document.write( '										 <li><a href=\"https://usdd.boards.net\" target=\"_blank\">USDD 論壇</a></li>	 \n' );
document.write( '										</ul> \n' );
document.write( '                                    </li>\n' );
document.write( '                                </ul>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"sb_bottom\"></div>\n' );
document.write( '                    </div>' );
